### ISSUE TITLE
Set kSecAttrAccessibleAlways

### ISSUE THREAD

**Issue by masterkain** [TheLevelUp/LUKeychainAccess#2]
I have been dealing with this issue for quite some time and I was baffled at why some of my users reported a blank object returning from the keychain while the phone was locked (we use background audio).

This answers it: http://stackoverflow.com/a/10583042/2448104

I think it is a worthy addition or at least be a preference.

**Comment by luizperes** [comment]
So was it fixed at all @cwalcott ?
