### ISSUE TITLE
Doesn't seem to work on iOS 8

### ISSUE THREAD

**Issue by batjo** [TheLevelUp/LUKeychainAccess#5]
I was testing to see if my app runs on iOS 8 and I noticed that username and password don't get stored properly.

```
[[LUKeychainAccess standardKeychainAccess] setString:@"hello" forKey:@"username"];
NSString *storedUsername = [[LUKeychainAccess standardKeychainAccess] stringForKey:@"username"];
NSLog(@"stored username %@, storedUsername);
```

When I run this code it will print stored username (null) instead of hello

**Comment by masterkain** [comment]
I have the same issue linking against 8.1. Will report back what I find.

**Comment by adly-holler** [comment]
Also seeing this using the iOS 9 SDK

**Comment by haemi** [comment]
@Adlai-Holler did you ever fix this? Some bugs I get reported really, really seem to come down to strings not stored properly (iOS 9).

**Comment by haemi** [comment]
any news on this?
